(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "ecb")
(depends-on "end-ruby-mode")
(depends-on "enh-ruby-mode")
(depends-on "grizzl")
(depends-on "noctilux-theme")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "racket-mode")
(depends-on "soft-morning-theme")
(depends-on "subatomic-theme")
